name: Deploy Infrastructure

on:
  push:
    branches: [ "develop" ]
  pull_request:

permissions:
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash 
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.5
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
    
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform