name: Deploy Infrastructure

on:
  push:
    branches: [ "develop" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash 

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::448035127556:role/rol-github #change to reflect your IAM role’s ARN
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
      
    - name: Sts GetCallerIdentity
      run: aws sts get-caller-identity

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
    
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform